import './globals.css'
import { Inter } from 'next/font/google'
import { Blobs, Nav } from './LayoutComponents'
import { Hero } from './Sections'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Nav />
      
      <Blobs />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      
    </html>
  )
}
